FROM golang:1.22

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

EXPOSE 4000

# Command to run the air executable
CMD ["air", "-c", ".air.toml"]
